# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('newfriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newfriend', to='main.User')),
                ('userfriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfriend', to='main.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
